version: '3.8'

services:
  backend:
    image: kimgyuill/recruit-backend:latest  # DockerHub 이미지 사용
    container_name: piro-recruit-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: piro-recruit-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=piro-recruit
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  backend: