version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: piro-recruit-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    restart: on-failure

  db:
    image: postgres:15
    container_name: piro-recruit-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=piro-recruit
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  backend:
