version: '3.8'

services:
  backend:
    image: kimgyuill/piro-recruiting:latest  # DockerHub 이미지 사용
    container_name: piro-recruit-app
    ports:
      - "8080:8080"
    # 외부 DB 사용으로 depends_on 불필요
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
    restart: always

  # DB는 외부에서 별도 관리 (Jenkins에서 환경변수로 DB 연결정보 주입)

networks:
  backend: