# application-prod.yml

spring:
  datasource:
    url: jdbc:postgresql://piro-recruit-db:5432/piro-recruit
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
