# application-prod.yml

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:34.64.113.7}:5432/piro-recruit
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
